version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      args:
        API_URL: ${API_URL}
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/share/nginx/html

  backend:
    build: ./backend
    ports:
      - "8080:5000"
    environment:
      - ALLOWED_ORIGIN=${FRONTEND_URL}
    volumes:
      - ./backend:/app
