version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: .docker/Dockerfile
    ports:
      - "80:80"
    environment:
      - API_URL=${API_URL:-http://localhost:8080}
    volumes:
      - ./frontend:/usr/share/nginx/html

  backend:
    build:
      context: ./backend
      dockerfile: .docker/Dockerfile
    ports:
      - "8080:5000"
    environment:
      - ALLOWED_ORIGIN=${FRONTEND_URL}
      - DEBUG=True
    volumes:
      - ./backend:/app
