version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/share/nginx/html

  backend:
    build: ./backend
    ports:
      - "8080:5000"
    environment:
      - ALLOWED_ORIGIN=http://localhost
    volumes:
      - ./backend:/app
