version: '3.8'
services:
  backend:
    container_name: ml-hello-world-backend
    build:
      context: ./../
      dockerfile: .docker/Dockerfile
    environment:
      - ALLOWED_ORIGIN=${FRONTEND_URL:-http://localhost}
    volumes:
      - ./backend:/app
    ports:
      - "8080:5000"
